<li style="margin-left:0px !important;"> <a href="[field:arcurl/]"><img src="[field:picname/]"  width="213" height="157"></a>
      <div class="li_tuandui_div">
        <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
        <span>集团执事董事</span>
        <div> 行  龄：7 年 <br/>
          行业简历：<br/>
          [field:info/]... </div>
        <a href="[field:arcurl/]" class="more_tuandui">点击查看+</a> </div>
    </li>