<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",621,656);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1011,1040);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",1137,1353);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='case_hover'>~typename~</a></li>";
$z[7]=Array("field","",1436,1455);
$z[7][4]['name']="title";
$z[8]=Array("field","",1496,1552);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[9]=Array("field","",1573,1593);
$z[9][4]['name']="writer";
$z[10]=Array("field","",1631,1649);
$z[10][4]['name']="body";
$z[11]=Array("include","",1784,1821);
$z[11][4]['filename']="footer.htm";

?>