<?php
$z[0]=Array("channel","\r\n      <li class=\"footer_dot\">|</li>\r\n      <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n      ",326,490);
$z[0][4]['type']="top";
$z[0][4]['noself']="yes";
$z[1]=Array("global","",647,673);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",686,710);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",732,753);
$z[3][4]['name']="cfg_dz";
$z[4]=Array("global","",778,800);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",811,832);
$z[5][4]['name']="cfg_dh";
$z[6]=Array("global","",843,864);
$z[6][4]['name']="cfg_cz";

?>