<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",635,670);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1029,1058);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",1156,1372);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='case_hover'>~typename~</a></li>";
$z[7]=Array("field","",1434,1455);
$z[7][4]['name']="content";
$z[8]=Array("include","",1550,1587);
$z[8][4]['filename']="footer.htm";

?>