<?php
$z[0]=Array("type","\r\n      <li> <a href=\"[field:typelink/]\"> <span>[field:typename/]</span> <font>SERVICE</font> <img src=\"/skin/images/menu_ahover.jpg\"> </a> </li>\r\n      ",482,669);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n      <li> <a href=\"[field:typelink/]\"> <span>[field:typename/]</span> <font>CASES</font> <img src=\"/skin/images/menu_ahover.jpg\"> </a> </li>\r\n      ",709,894);
$z[1][4]['typeid']="9";
$z[2]=Array("type","\r\n      <li> <a href=\"[field:typelink/]\"> <span>[field:typename/]</span> <font>DESIGNER</font> <img src=\"/skin/images/menu_ahover.jpg\"> </a> </li>\r\n      ",934,1123);
$z[2][4]['typeid']="14";
$z[3]=Array("type","\r\n      <li> <a href=\"[field:typelink/]\"> <span>[field:typename/]</span> <font>SUBJECT</font> <img src=\"/skin/images/menu_ahover.jpg\"> </a> </li>\r\n      ",1163,1351);
$z[3][4]['typeid']="18";
$z[4]=Array("type","\r\n      <li> <a href=\"[field:typelink/]\"> <span>[field:typename/]</span> <font>NEWS</font> <img src=\"/skin/images/menu_ahover.jpg\"> </a> </li>\r\n      ",1391,1576);
$z[4][4]['typeid']="22";
$z[5]=Array("type","\r\n      <li> <a href=\"[field:typelink/]\"> <span>[field:typename/]</span> <font>ABOUT US</font> <img src=\"/skin/images/menu_ahover.jpg\"> </a> </li>\r\n      ",1616,1805);
$z[5][4]['typeid']="26";

?>