<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",637,672);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1047,1076);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",1174,1390);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='case_hover'>~typename~</a></li>";
$z[7]=Array("list","\r\n        <li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"312\" height=\"182\" /><span> <b>[field:title/]</b>\r\n          <p>[field:description function='cn_substr(@me,60)'/]...</p>\r\n          </span></a></li>\r\n        ",1497,1765);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",1850,1903);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("include","",4278,4315);
$z[9][4]['filename']="footer.htm";

?>