<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",637,672);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1047,1076);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        ",1173,1389);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='case_hover'>~typename~</a></li>";
$z[7]=Array("arclist","\r\n        <li><img src=\"[field:picname/]\"  width=\"213\" height=\"157\" /><span>\r\n          <h2>[field:title/]</h2>\r\n          <b>集团执事董事</b>\r\n          <p>行龄：7 年<br />\r\n            行业简历：<br />\r\n            <span>[field:info/]... </p>\r\n          </span> <a href=\"[field:arcurl/]\"><img src=\"/skin/images/tuandui_more.jpg\" /></a></li>\r\n        ",1496,1923);
$z[7][4]['infolen']="60";
$z[7][4]['row']="4";
$z[7][4]['typeid']="15";
$z[8]=Array("include","",5184,5221);
$z[8][4]['filename']="footer.htm";

?>